language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: openjdk11
      dist: xenial
      services:
      - xvfb
    - os: osx
      osx_image: xcode9.3 # JDK 1.8.0_112-b16
      if: type IN (pull_request)

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

install: true

before_install:
# - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
 - echo $JAVA_HOME

# Build on MacOSX is triggered only for pull requests
script:
 - export
 - bash -e ./travis_build.sh
